const projects={
  'brick-kiln-workers':{number:'01',title:'Brick Kiln Workers Welfare',tagline:'Dignity, protection and opportunity for families working in brick kilns.',image:'../assets/projects-1-4.webp',position:'0 0',intro:'Brick kiln workers often face unsafe conditions, unstable incomes and limited access to essential services. We work directly with families to provide practical welfare assistance while protecting their dignity.',body:'Our programme responds to immediate needs with food packages, protective supplies, health support and help accessing education for children. By listening to workers and partnering with local communities, we aim to reduce hardship and create safer pathways for the next generation.',focus:['Protective clothing and equipment','Food and emergency assistance','Medical support for workers','Education support for children'],quote:'Every worker deserves safety, respect and the chance to build a better future for their family.'},
  'free-medical-camps':{number:'02',title:'Free Medical Camps & Treatment',tagline:'Bringing compassionate healthcare closer to underserved communities.',image:'../assets/projects-1-4.png',position:'100% 0',intro:'For families living far from affordable healthcare, a basic consultation can be out of reach. Our free medical camps bring qualified care directly into underserved neighbourhoods.',body:'Medical teams provide consultations, basic screening, essential medicines and referrals for continued treatment. We focus on respectful, accessible care and help families understand the next steps for managing their health.',focus:['Free doctor consultations','Basic health screening','Essential medicines','Treatment referrals and follow-up'],quote:'Timely medical attention can prevent a manageable condition from becoming a family crisis.'},
  'clean-water':{number:'03',title:'Clean Water, Filters & Water Pumps',tagline:'Safe water solutions designed with and for local communities.',image:'../assets/projects-1-4.png',position:'0 100%',intro:'Clean water is fundamental to health, education and household stability. We install practical water solutions in communities where safe sources are limited or unreliable.',body:'Projects include hand pumps, filtration systems and community water points selected according to local conditions. We involve residents in planning and maintenance so each installation remains useful long after it is completed.',focus:['Community hand pumps','Household and shared filters','Water quality awareness','Local maintenance support'],quote:'A reliable source of clean water changes every part of daily life.'},
  'education-scholarships':{number:'04',title:'Education & Scholarships',tagline:'Helping children and young people remain in education and realise their potential.',image:'../assets/projects-1-4.png',position:'100% 100%',intro:'Financial hardship should not decide whether a child can learn. Our education programme supports students whose families cannot meet the cost of school.',body:'We provide scholarships, books, uniforms and essential learning materials. Support is directed toward meaningful continuity—helping students attend consistently, progress confidently and pursue opportunities beyond the classroom.',focus:['School fee assistance','Books and learning materials','Uniforms and supplies','Merit and need-based scholarships'],quote:'Education gives a young person choices that poverty tries to take away.'},
  'orphans-widows-support':{number:'05',title:'Orphans & Widows Monthly Support',tagline:'Reliable monthly help for households carrying the greatest responsibilities.',image:'../assets/projects-5-8.png',position:'0 0',intro:'Widows and orphaned children can face sustained financial pressure and social vulnerability. Consistent monthly support helps families plan, remain stable and meet essential needs.',body:'Assistance may include groceries, household essentials, education costs and urgent welfare needs. We deliver support respectfully and work to understand each family’s circumstances rather than applying a one-size-fits-all response.',focus:['Monthly grocery packages','Household essentials','Children’s education support','Emergency family assistance'],quote:'Consistency brings families more than supplies—it brings security and peace of mind.'},
  'women-empowerment':{number:'06',title:'Women Empowerment & Sewing Machines',tagline:'Practical skills and tools that help women build independent livelihoods.',image:'../assets/projects-5-8.png',position:'100% 0',intro:'When women have income-generating skills and the right equipment, the benefits extend throughout their families and communities.',body:'Our programme combines tailoring instruction with sewing-machine support for eligible women. Participants develop practical skills they can use from home or in local work, creating a sustainable source of income with dignity.',focus:['Tailoring and sewing training','Sewing-machine provision','Home-based livelihood support','Practical business guidance'],quote:'A sewing machine can become a tool for confidence, income and lasting independence.'},
  'marriage-support':{number:'07',title:'Marriage Support for Deserving Families',tagline:'Respectful assistance that helps families celebrate without unmanageable debt.',image:'../assets/projects-5-8.png',position:'0 100%',intro:'For families experiencing poverty, essential marriage costs can create severe financial pressure. We provide modest, respectful support based on genuine need.',body:'Assistance focuses on practical household and ceremony essentials rather than extravagance. Every case is handled discreetly, helping families begin a new chapter without being pushed deeper into debt.',focus:['Essential household items','Modest ceremony assistance','Needs-based family support','Private and dignified delivery'],quote:'Support offered with respect allows a joyful occasion to remain a source of hope.'},
  'religious-leader-support':{number:'08',title:'Support for Deserving Religious Leader',tagline:'Honouring community service through discreet and practical welfare support.',image:'../assets/projects-5-8.png',position:'100% 100%',intro:'Religious leaders often serve their communities with limited personal income. Where genuine need exists, we provide practical assistance with care and discretion.',body:'Support may include groceries, healthcare assistance and essential household needs. The programme is based on financial need and community service, and assistance is provided without political or sectarian discrimination.',focus:['Monthly grocery assistance','Healthcare support','Essential household needs','Respectful, needs-based assessment'],quote:'Those who support their communities should not be left alone in times of hardship.'}
};
const originalProjectPhotos={
  'brick-kiln-workers':'../assets/photos/field-01.jpg',
  'free-medical-camps':'../assets/project-photos/medical-camp.jpg',
  'clean-water':'../assets/project-photos/clean-water.jpg',
  'education-scholarships':'../assets/project-photos/education.jpg',
  'orphans-widows-support':'../assets/project-photos/widows.jpg',
  'women-empowerment':'../assets/photos/field-02.jpg',
  'marriage-support':'../assets/photos/field-05.jpg',
  'religious-leader-support':'../assets/project-photos/religious-leader.jpg'
};
Object.entries(originalProjectPhotos).forEach(([projectKey,image])=>{projects[projectKey].image=image;projects[projectKey].position='center'});
const key=document.body.dataset.project;
const project=projects[key];
if(project){
  project.image=project.image.replace('.png','.webp');
  let description=document.querySelector('meta[name="description"]');
  if(!description){description=document.createElement('meta');description.name='description';document.head.appendChild(description)}
  description.content=project.tagline;
  if(!document.querySelector('link[rel="icon"]')){const icon=document.createElement('link');icon.rel='icon';icon.type='image/svg+xml';icon.href='../assets/favicon.svg';document.head.appendChild(icon)}
  document.querySelector('[data-number]').textContent=project.number;
  document.querySelector('[data-title]').textContent=project.title;
  document.querySelector('[data-tagline]').textContent=project.tagline;
  document.querySelector('[data-intro]').textContent=project.intro;
  document.querySelector('[data-body]').textContent=project.body;
  document.querySelector('[data-quote]').textContent=project.quote;
  document.querySelector('[data-focus]').innerHTML=project.focus.map(item=>`<li>${item}</li>`).join('');
  const hero=document.querySelector('.project-hero');hero.style.backgroundImage=`url('${project.image}')`;hero.style.backgroundPosition=project.position;
}
